name: targetpred
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- autopep8
- jupyter
- jupyterlab
- scikit-learn
- pandas
- numpy
- scipy
- tensorflow-gpu
- keras
- matplotlib
- seaborn
- jupyter_contrib_nbextensions
- feather-format
- ujson
- pip:
    - ijson
